#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Generates the per-camera half of the compose stack from cameras.yml.

Everything else in docker-compose.yml is hand-written and does not repeat
per camera. The source adapters do - one container each, ten of them - and
writing those by hand is how a camera ends up with the wrong SOURCE_ID.

    uv run analytics/compose_gen.py            # write the file
    uv run analytics/compose_gen.py --check    # fail if it is out of date

The check mode is what CI runs, so an edit to cameras.yml that nobody
regenerated does not ship.

It also validates the geometry, and it validates it loudly. A missing
recording is the expensive failure: Docker answers a bind mount whose source
does not exist by creating a DIRECTORY there, `ls` then shows what looks like
a file, and ffmpeg fails several layers away with `Is a directory`. Nothing
here bind-mounts a file - the whole directory is mounted - but the same
missing file still produces a dead stream, so it is caught here instead.
"""

import argparse
import pathlib
import sys

import yaml

_ROOT = pathlib.Path(__file__).resolve().parent.parent
_CAMERAS_YML = _ROOT / 'analytics' / 'cameras.yml'
_OUTPUT = _ROOT / 'docker-compose.analytics.yml'
_VIDEO_DIR = _ROOT / 'videos' / 'cctv'

# A recording smaller than this is a truncated download, not a video. The
# real ones are 130-430 MB for an hour of 720p15 HEVC.
_MIN_VIDEO_BYTES = 1_000_000

_HEADER = """\
# GENERATED by `uv run analytics/compose_gen.py` from analytics/cameras.yml.
# Do not edit: run the generator. `--check` fails when this is out of date.
#
# One Savant source adapter per camera. They read RTSP from MediaMTX rather
# than the mp4 files directly - reading the files would be cheaper and would
# make browser overlays permanently impossible, because Savant and MediaMTX
# would each loop the same recording independently and drift apart within
# minutes. Both have to watch the same decoded stream.
"""


class ConfigError(Exception):
	"""cameras.yml describes something that cannot work."""


class _Quoted(str):
	"""A string that is always emitted quoted.

	PyYAML leaves `09` bare, because YAML 1.1 does not read it as a
	number - `9` is not an octal digit. Docker Compose's parser does read
	it as one, so `SOURCE_ID: 09` reaches the adapter as `9`, every row
	that camera produces lands under a source_id the catalogue has never
	heard of, and the camera silently contributes to nothing. Quoting
	every environment value costs one representer and closes the whole
	class of bug.
	"""


yaml.add_representer(
	_Quoted,
	lambda dumper, data: dumper.represent_scalar(
		'tag:yaml.org,2002:str', str(data), style="'"
	),
	Dumper=yaml.SafeDumper,
)


def load_config(path: pathlib.Path = _CAMERAS_YML) -> dict:
	"""Reads and validates cameras.yml.

	Args:
		path: The config file.

	Returns:
		The parsed document.

	Raises:
		ConfigError: A camera, zone or line is unusable.
	"""
	config = yaml.safe_load(path.read_text())
	cameras = config.get('cameras') or {}
	if not cameras:
		raise ConfigError(f'{path}: no cameras')
	for camera_id, camera in cameras.items():
		if not isinstance(camera_id, str):
			raise ConfigError(
				f'camera id {camera_id!r} is not a string - quote it, or '
				"'09' parses as the number 9 and stops matching the "
				'catalogue'
			)
		if not camera.get('stream'):
			raise ConfigError(f'camera {camera_id}: no stream')
	_check_geometry(config, set(cameras))
	return config


def _check_points(where: str, points: object) -> None:
	"""Rejects a polygon or line that cannot be drawn.

	Args:
		where: What is being checked, for the error message.
		points: The candidate list of [x, y] pairs.

	Raises:
		ConfigError: Too few points, or a coordinate outside 0..1.
	"""
	if not isinstance(points, list) or len(points) < 2:
		raise ConfigError(f'{where}: needs at least two points')
	for point in points:
		if not isinstance(point, list) or len(point) != 2:
			raise ConfigError(f'{where}: {point!r} is not an [x, y] pair')
		if not all(0.0 <= value <= 1.0 for value in point):
			raise ConfigError(
				f'{where}: {point!r} is outside 0..1 - coordinates are '
				'normalised against the frame, not pixels'
			)


def _segments_cross(
	a: list[float], b: list[float], c: list[float], d: list[float]
) -> bool:
	"""Reports whether segments a-b and c-d properly intersect."""
	def side(p, q, r):
		return (q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0])

	d1, d2 = side(c, d, a), side(c, d, b)
	d3, d4 = side(a, b, c), side(a, b, d)
	return ((d1 > 0) != (d2 > 0)) and ((d3 > 0) != (d4 > 0))


def _check_polygon(where: str, points: list) -> None:
	"""Rejects a polygon that is a bow-tie.

	Args:
		where: What is being checked, for the error message.
		points: The vertices, in order.

	Raises:
		ConfigError: Fewer than three vertices, or two edges cross.

	A hand-written vertex list very easily describes a bow-tie, and a
	self-intersecting polygon makes point-in-polygon answer nonsense
	rather than fail - so it is caught here, where it is visible.
	"""
	_check_points(where, points)
	if len(points) < 3:
		raise ConfigError(f'{where}: a polygon needs at least three points')
	count = len(points)
	edges = [(points[i], points[(i + 1) % count]) for i in range(count)]
	for i, (a, b) in enumerate(edges):
		for j, (c, d) in enumerate(edges):
			# Adjacent edges share a vertex and always "touch".
			if j <= i or (j - i) % count <= 1 or (i - j) % count <= 1:
				continue
			if _segments_cross(a, b, c, d):
				raise ConfigError(
					f'{where}: edges {i} and {j} cross - the vertices are '
					'out of order and this polygon is a bow-tie'
				)


def _check_geometry(config: dict, camera_ids: set[str]) -> None:
	"""Validates every zone and line against the camera list.

	Args:
		config: The parsed cameras.yml.
		camera_ids: Every declared camera id.

	Raises:
		ConfigError: A zone or line names an unknown camera, or its
			points are unusable.
	"""
	for zone_name, parts in (config.get('zones') or {}).items():
		for index, part in enumerate(parts):
			where = f'zone {zone_name}[{index}]'
			if part.get('camera') not in camera_ids:
				raise ConfigError(
					f'{where}: unknown camera {part.get("camera")!r}'
				)
			_check_polygon(where, part.get('points'))
	for line_name, line in (config.get('lines') or {}).items():
		if line.get('camera') not in camera_ids:
			raise ConfigError(
				f'line {line_name}: unknown camera {line.get("camera")!r}'
			)
		for side in ('outer', 'inner'):
			if side not in line:
				raise ConfigError(
					f'line {line_name}: no {side} line. Footfall needs two '
					'parallel lines crossed in order; one line and a '
					'jittering box produce phantom crossings.'
				)
			_check_points(f'line {line_name}.{side}', line[side])


def link_recordings(config: dict, video_dir: pathlib.Path) -> list[str]:
	"""Points `camN.mp4` at each camera's real recording.

	Args:
		config: The parsed cameras.yml.
		video_dir: Where the recordings live.

	Returns:
		A line per camera describing what was linked, for the log.

	Raises:
		ConfigError: A camera has no recording, or has a truncated one.

	MediaMTX serves one regex path for every camera and reads
	`/videos/$MTX_PATH.mp4`, but the recordings are named with the hour
	they were captured. Rather than mount ten files under ten names - the
	bind mount whose missing source silently becomes a directory - the
	whole directory is mounted and each camera gets a sibling symlink.
	"""
	report = []
	for camera_id, camera in config['cameras'].items():
		stream = camera['stream']
		link = video_dir / f'{stream}.mp4'
		matches = sorted(
			path
			for path in video_dir.glob(f'{stream}_*.mp4')
			if not path.is_symlink()
		)
		if not matches:
			raise ConfigError(
				f'camera {camera_id} ({stream}): no recording matching '
				f'{video_dir}/{stream}_*.mp4'
			)
		source = matches[-1]
		size = source.stat().st_size
		if size < _MIN_VIDEO_BYTES:
			raise ConfigError(
				f'camera {camera_id}: {source} is {size} bytes, under the '
				f'{_MIN_VIDEO_BYTES}-byte floor - a truncated download, '
				'not a recording'
			)
		if link.is_symlink():
			link.unlink()
		elif link.exists():
			raise ConfigError(
				f'{link} exists and is not a symlink - refusing to replace '
				'what might be a real recording'
			)
		link.symlink_to(source.name)
		report.append(f'{link.name} -> {source.name} ({size // 1_000_000} MB)')
	return report


def render(config: dict) -> str:
	"""Builds the generated compose file.

	Args:
		config: The parsed cameras.yml.

	Returns:
		The YAML document, header comment included.
	"""
	services = {}
	for camera_id, camera in config['cameras'].items():
		services[f'savant-source-{camera_id}'] = {
			'image': 'ghcr.io/insight-platform/savant-adapters-gstreamer:latest',
			'entrypoint': '/opt/savant/adapters/gst/sources/rtsp.sh',
			'environment': {
				'RTSP_URI': _Quoted(f'rtsp://cameras:8554/{camera["stream"]}'),
				'RTSP_TRANSPORT': _Quoted('tcp'),
				# The BACKEND's camera id, not MediaMTX's path: every row in
				# ClickHouse then joins to catalogue.py with no lookup table,
				# and cameras.yml stays the one place the two namespaces meet.
				'SOURCE_ID': _Quoted(camera_id),
				# DEALER/ROUTER, not PUB/SUB: these frames are H.264 and
				# PUB/SUB drops without backpressure, so a dropped keyframe
				# corrupts every frame after it. TCP, not ipc://, because an
				# ipc endpoint is a file: when the module rebinds it, every
				# adapter is left holding a socket that no longer exists and
				# the pipeline wedges until all of them are restarted.
				'ZMQ_ENDPOINT': _Quoted(
					'dealer+connect:tcp://savant-module:5555'
				),
				# Mandatory. Savant's pts is stream-relative by default and
				# resets on reconnect; without this no stored timestamp can be
				# joined to a recording or to EXT-X-PROGRAM-DATE-TIME, and
				# every row written is worthless.
				'USE_ABSOLUTE_TIMESTAMPS': _Quoted('True'),
				# Die on a stalled feed so compose restarts the one adapter,
				# rather than sitting on a stream that stopped delivering.
				'STALL_ACTION': _Quoted('fail'),
				# BUFFER_LEN is left at its default 50. It is tempting to cut
				# it - the queue sits near full, and fifty frames at 15 fps is
				# three seconds of the metadata path's latency - but it is the
				# adapter's OUTBOUND queue, and this adapter drops rather than
				# blocks when it fills. At 10 every camera logged "Sink queue
				# is full, the frame is skipped" continuously and the pipeline
				# stored nothing at all. The latency is dealt with where it can
				# be dealt with safely: the player sits further back from the
				# live edge (see CameraGridView), so the boxes are always in
				# the database before the frame they describe is on screen.
				'LOGLEVEL': _Quoted('info'),
			},
			'depends_on': {
				'savant-module': {'condition': 'service_healthy'},
				'cameras': {'condition': 'service_started'},
			},
			'restart': 'unless-stopped',
		}
	body = yaml.safe_dump(
		{'services': services}, sort_keys=False, width=100
	)
	return _HEADER + '\n' + body


def main(argv: list[str] | None = None) -> int:
	"""Writes or checks the generated compose file.

	Args:
		argv: Command-line arguments, for tests.

	Returns:
		A process exit code.
	"""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument(
		'--check',
		action='store_true',
		help='exit non-zero if the generated file is out of date',
	)
	args = parser.parse_args(argv)

	try:
		config = load_config()
		rendered = render(config)
		if args.check:
			current = _OUTPUT.read_text() if _OUTPUT.exists() else ''
			if current != rendered:
				print(
					f'{_OUTPUT.name} is out of date - run '
					'`uv run analytics/compose_gen.py`',
					file=sys.stderr,
				)
				return 1
			print(f'{_OUTPUT.name} is up to date')
			return 0
		for line in link_recordings(config, _VIDEO_DIR):
			print(line)
		_OUTPUT.write_text(rendered)
		print(f'wrote {_OUTPUT.name}: {len(config["cameras"])} source adapters')
	except ConfigError as error:
		print(f'error: {error}', file=sys.stderr)
		return 1
	return 0


if __name__ == '__main__':
	raise SystemExit(main())
