#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Generates the per-camera half of the compose stack from cameras.yml.

Everything else in docker-compose.yml is hand-written and does not repeat
per camera. The source adapters do - one container each, ten of them - and
writing those by hand is how a camera ends up with the wrong SOURCE_ID.

    uv run scripts/compose_gen.py            # write the file
    uv run scripts/compose_gen.py --check    # fail if it is out of date

The check mode is what CI runs, so an edit to cameras.yml that nobody
regenerated does not ship.

It also validates the geometry, and it validates it loudly. A missing
recording is the expensive failure: Docker answers a bind mount whose source
does not exist by creating a DIRECTORY there, `ls` then shows what looks like
a file, and ffmpeg fails several layers away with `Is a directory`. Nothing
here bind-mounts a file - the whole directory is mounted - but the same
missing file still produces a dead stream, so it is caught here instead.
"""

import argparse
import pathlib
import sys

import yaml

_ROOT = pathlib.Path(__file__).resolve().parent.parent
# The service's own loader, so the generator validates exactly what the
# service will accept. It needs nothing this script does not already have -
# yaml and the standard library - and duplicating its ninety lines of
# geometry checks here is how the two drift into disagreeing about which
# configs are legal.
sys.path.insert(0, str(_ROOT / 'libs' / 'ain_analytics'))

from ain_analytics import config as ain_config  # noqa: E402

ConfigError = ain_config.ConfigError

_CAMERAS_YML = _ROOT / 'config' / 'cameras.yml'
_OUTPUT = _ROOT / 'docker-compose.analytics.yml'
_VIDEO_DIR = _ROOT / 'videos' / 'cctv'

# A recording smaller than this is a truncated download, not a video. The
# real ones are 130-430 MB for an hour of 720p15 HEVC.
_MIN_VIDEO_BYTES = 1_000_000

_HEADER = """\
# GENERATED by `uv run scripts/compose_gen.py` from config/cameras.yml.
# Do not edit: run the generator. `--check` fails when this is out of date.
#
# One Savant source adapter per camera. They read RTSP from MediaMTX rather
# than the mp4 files directly - reading the files would be cheaper and would
# make browser overlays permanently impossible, because Savant and MediaMTX
# would each loop the same recording independently and drift apart within
# minutes. Both have to watch the same decoded stream.
"""


class _Quoted(str):
	"""A string that is always emitted quoted.

	PyYAML leaves `09` bare, because YAML 1.1 does not read it as a
	number - `9` is not an octal digit. Docker Compose's parser does read
	it as one, so `SOURCE_ID: 09` reaches the adapter as `9`, every row
	that camera produces lands under a source_id the catalogue has never
	heard of, and the camera silently contributes to nothing. Quoting
	every environment value costs one representer and closes the whole
	class of bug.
	"""


yaml.add_representer(
	_Quoted,
	lambda dumper, data: dumper.represent_scalar(
		'tag:yaml.org,2002:str', str(data), style="'"
	),
	Dumper=yaml.SafeDumper,
)


def load_config(path: pathlib.Path = _CAMERAS_YML) -> dict:
	"""Reads cameras.yml, validating it the way the service will.

	Args:
		path: The config file.

	Returns:
		The raw parsed document, which is what the renderer needs.

	Raises:
		ConfigError: A camera, zone or line is unusable - including a
			bow-tie polygon, which the loader rejects because
			pointInPolygon answers nonsense for one rather than failing.
	"""
	# Loaded twice on purpose: once through the service's loader for its
	# validation, once raw because the renderer wants the document as
	# written rather than the parsed objects.
	ain_config.load(path)
	return yaml.safe_load(path.read_text())


def link_recordings(config: dict, video_dir: pathlib.Path) -> list[str]:
	"""Points `camN.mp4` at each camera's real recording.

	Args:
		config: The parsed cameras.yml.
		video_dir: Where the recordings live.

	Returns:
		A line per camera describing what was linked, for the log.

	Raises:
		ConfigError: A camera has no recording, or has a truncated one.

	MediaMTX serves one regex path for every camera and reads
	`/videos/$MTX_PATH.mp4`, but the recordings are named with the hour
	they were captured. Rather than mount ten files under ten names - the
	bind mount whose missing source silently becomes a directory - the
	whole directory is mounted and each camera gets a sibling symlink.
	"""
	report = []
	for camera_id, camera in config['cameras'].items():
		stream = camera['stream']
		link = video_dir / f'{stream}.mp4'
		matches = sorted(
			path
			for path in video_dir.glob(f'{stream}_*.mp4')
			if not path.is_symlink()
		)
		if not matches:
			raise ConfigError(
				f'camera {camera_id} ({stream}): no recording matching '
				f'{video_dir}/{stream}_*.mp4'
			)
		source = matches[-1]
		size = source.stat().st_size
		if size < _MIN_VIDEO_BYTES:
			raise ConfigError(
				f'camera {camera_id}: {source} is {size} bytes, under the '
				f'{_MIN_VIDEO_BYTES}-byte floor - a truncated download, '
				'not a recording'
			)
		if link.is_symlink():
			link.unlink()
		elif link.exists():
			raise ConfigError(
				f'{link} exists and is not a symlink - refusing to replace '
				'what might be a real recording'
			)
		link.symlink_to(source.name)
		report.append(f'{link.name} -> {source.name} ({size // 1_000_000} MB)')
	return report


def render(config: dict) -> str:
	"""Builds the generated compose file.

	Args:
		config: The parsed cameras.yml.

	Returns:
		The YAML document, header comment included.
	"""
	services = {}
	for camera_id, camera in config['cameras'].items():
		services[f'savant-source-{camera_id}'] = {
			# Pinned by digest: an adapter is one end of a versioned message
			# format and the module is the other, so neither may float.
			'image': (
				'ghcr.io/insight-platform/savant-adapters-gstreamer@sha256:bc0d9fc73999ee7411183b783df53335af1bebb7161b981f0b175dfc3a3d1d47'
			),
			'entrypoint': '/opt/savant/adapters/gst/sources/rtsp.sh',
			'environment': {
				'RTSP_URI': _Quoted(f'rtsp://cameras:8554/{camera["stream"]}'),
				'RTSP_TRANSPORT': _Quoted('tcp'),
				# The BACKEND's camera id, not MediaMTX's path: every row in
				# ClickHouse then joins to catalogue.py with no lookup table,
				# and cameras.yml stays the one place the two namespaces meet.
				'SOURCE_ID': _Quoted(camera_id),
				# DEALER/ROUTER, not PUB/SUB: these frames are H.264 and
				# PUB/SUB drops without backpressure, so a dropped keyframe
				# corrupts every frame after it. TCP, not ipc://, because an
				# ipc endpoint is a file: when the module rebinds it, every
				# adapter is left holding a socket that no longer exists and
				# the pipeline wedges until all of them are restarted.
				'ZMQ_ENDPOINT': _Quoted(
					'dealer+connect:tcp://savant-module:5555'
				),
				# Mandatory. Savant's pts is stream-relative by default and
				# resets on reconnect; without this no stored timestamp can be
				# joined to a recording or to EXT-X-PROGRAM-DATE-TIME, and
				# every row written is worthless.
				'USE_ABSOLUTE_TIMESTAMPS': _Quoted('True'),
				# Die on a stalled feed so compose restarts the one adapter,
				# rather than sitting on a stream that stopped delivering.
				'STALL_ACTION': _Quoted('fail'),
				# BUFFER_LEN is left at its default 50. It is tempting to cut
				# it - the queue sits near full, and fifty frames at 15 fps is
				# three seconds of the metadata path's latency - but it is the
				# adapter's OUTBOUND queue, and this adapter drops rather than
				# blocks when it fills. At 10 every camera logged "Sink queue
				# is full, the frame is skipped" continuously and the pipeline
				# stored nothing at all. The latency is dealt with where it can
				# be dealt with safely: the player sits further back from the
				# live edge (see CameraGridView), so the boxes are always in
				# the database before the frame they describe is on screen.
				'LOGLEVEL': _Quoted('info'),
			},
			'depends_on': {
				'savant-module': {'condition': 'service_healthy'},
				'cameras': {'condition': 'service_started'},
			},
			'restart': 'unless-stopped',
		}
	body = yaml.safe_dump(
		{'services': services}, sort_keys=False, width=100
	)
	return _HEADER + '\n' + body


def main(argv: list[str] | None = None) -> int:
	"""Writes or checks the generated compose file.

	Args:
		argv: Command-line arguments, for tests.

	Returns:
		A process exit code.
	"""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument(
		'--check',
		action='store_true',
		help='exit non-zero if the generated file is out of date',
	)
	args = parser.parse_args(argv)

	try:
		config = load_config()
		rendered = render(config)
		if args.check:
			current = _OUTPUT.read_text() if _OUTPUT.exists() else ''
			if current != rendered:
				print(
					f'{_OUTPUT.name} is out of date - run '
					'`uv run scripts/compose_gen.py`',
					file=sys.stderr,
				)
				return 1
			print(f'{_OUTPUT.name} is up to date')
			return 0
		for line in link_recordings(config, _VIDEO_DIR):
			print(line)
		_OUTPUT.write_text(rendered)
		print(f'wrote {_OUTPUT.name}: {len(config["cameras"])} source adapters')
	except ConfigError as error:
		print(f'error: {error}', file=sys.stderr)
		return 1
	return 0


if __name__ == '__main__':
	raise SystemExit(main())
